### PR TITLE
feat: adds in max args checking; also removes duplicate command validation

### PR DESCRIPTION
**Pull request by BHSDuncan**
Also now properly validates min_args; re-orders validation to allow argument descriptor validation to always be done first; misc. cleanup of error strings

### CODE REVIEW

**Comment by balloonpopper** [comment]
Passing lots of parameters to stop correctly fails regardless of spacing between parameters

Too many parameters failed as expected - 
```
 2022-4-12T234536 (E)	Errors in file ESCCommandArgumentDescriptor:validate()
Invalid arguments for command say
Maximum number of arguments (3) exceeded: [player, "t", floating, floating]
```

Optional parameter worked correctly as expected
```
say player "t" floating 

2022-4-12T235143 (D)	Running command say with parameters [player, "t", floating] 
```

Optional parameter removed worked as expected
```
say player "t"

2022-4-12T235235 (D)	Running command say with parameters [player, "t", ]
```

Missing required parameter failed as expected
```
say player 

Invalid arguments for command say
Arguments didn't match minimum size 2: Only 1 was found
```

2 Missing parameters failed as expected
```
say

Invalid arguments for command say
Arguments didn't match minimum size 2: Only 0 were found
```

**Comment by balloonpopper** [comment]
The "wait" command worked/failed as expected. Passing lots of numbers ("wait 0.5555555") worked correctly, multiple numbers failed, swapping strings and values for parameters 1 and 2 worked as expected.

Concatenating valid commands failed as expected (wait 1 stop)

Invalid commands fail as expected
```
wai t 5

Invalid command detected: wai
Command implementation not found in any command directory
```

Short of testing passing too few/too many/correct number of parameters to every command, the general pattern appears to work

The only unexpected error was that "wait .5" was interpreted as a string, but that's outside the scope of this PR and will be raised separately.

**Review by StraToN — APPROVED** [review]
Great changes! Not tested yet, but code review is fine by me.
@balloonpopper Thanks for your thorough testing!

**Comment by BHSDuncan** [comment]
The latest commit addresses issue 230 and also adds in some validation for 'wait' (ensures a positive number is specified).

**Comment by balloonpopper** [comment]
Retested using latest commit [9b30551](https://github.com/godot-escoria/escoria-demo-game/pull/569/commits/9b30551b8fbe3f2b2f23c304465035726b0fa474)

The issue 230 fix worked. This script now works correctly and didn't allow input for 1/2 second
```
accept_input NONE
wait .5
accept_input ALL
```

------
Regression tests all passed :

Passing lots of parameters to "stop" correctly fails regardless of spacing between parameters

Too many parameters failed as expected 

Optional parameter worked correctly as expected

Optional parameter removed worked as expected

Missing required parameter failed as expected

2 Missing parameters failed as expected

**Review by balloonpopper — APPROVED** [review]

**Comment by StraToN** [comment]
Many thanks!! :partying_face:

**Pull request merged**
