### PR TITLE
fix: ESCItem that is a trigger should not capture input events

### PR DESCRIPTION
**Pull request by bolinfest**
Fixes https://github.com/godot-escoria/escoria-issues/issues/147

### CODE REVIEW

**Comment by bolinfest** [comment]
If you trace through the code, in `ESCItem._ready()`, signals such as `mouse_left_clicked_item` are wired up *only* when `!is_trigger`. Therefore, in `ESCItem._unhandled_input()`, there is no reason to exercise the `emit_signal` calls when `is_trigger` is `true`. At least in this case, it also appears that the `get_tree().set_input_as_handled()` calls are working *against* us, so we should just bail out altogether.

**Comment by balloonpopper** [comment]
Confirmed that this fixes the issue in the new version of room 7 (https://github.com/godot-escoria/escoria-demo-game/pull/514)

**Review by BHSDuncan — APPROVED** [review]
Looks good to me, though the other guys will be able to better test this.

**Review by dploeger — APPROVED** [review]
Looks good to me as well. Thanks a lot. 🎁

**Pull request merged**
