### PR TITLE
feat: Updated room 9 graphics

### PR DESCRIPTION
**Pull request by balloonpopper**
image

### CODE REVIEW

**Review by dploeger — APPROVED** [review]
I really like your creativity here. 🙂

**Review by BHSDuncan — APPROVED** [review]

**Review by StraToN — APPROVED** [review]

**Comment by StraToN** [comment]
Unfortunately there is a conflict in room10.tscn since we merged #529. @balloonpopper Can you rebase please? Thanks a lot!

**Comment by balloonpopper** [comment]
Done @StraToN

**Comment by StraToN** [comment]
Great! Thanks a lot! :partying_face:

**Pull request merged**
