### PR TITLE
feat: performs basic validation for ESCAnimationResource in-editor an…

### PR DESCRIPTION
**Pull request by BHSDuncan**
…d in-game

fixes https://github.com/godot-escoria/escoria-issues/issues/214

### CODE REVIEW

**Comment by StraToN** [comment]
@BHSDuncan To be rebased onto develop branch, and verify the fix is still there. Thanks!

**Review by StraToN — APPROVED** [review]

**Comment by BHSDuncan** [comment]
Rebased with zero issues! Sounds too good to be true...

**Comment by balloonpopper** [comment]
Narrator : "It was in fact, too good to be true..."

**Review by balloonpopper — APPROVED** [review]
Tested - works great!

**Comment by BHSDuncan** [comment]
I suppose it's asking too much for Git to know that the NEW code should make use of the rebased code's changes. #firstworldcodingproblems

**Pull request merged**
