### PR TITLE
fix: disallows input during any transition call

### PR DESCRIPTION
**Pull request by BHSDuncan**
Closes https://github.com/godot-escoria/escoria-issues/issues/275

### CODE REVIEW

**Comment by balloonpopper** [comment]
On the positive side, this fixes issue 275. 
On the negative side I found that if you :
Run room 1 using F6 and curtain transition, followed by feverishly clicking the right hand doorway lots of times while the transition-in is happening, the transition-in breaks.
Error in esc_event_manager.gd, line 311.

image

Console output:
```
ESC (2022-07-22T18:25:42) I esc_group.gd: Interrupting event group ([Reference:3091]).
ESC (2022-07-22T18:25:42) W turn_to.gd: [turn_to] interrupt() function not implemented.
WARNING: ESC (2022-07-22T18:25:42) W turn_to.gd: [turn_to] interrupt() function not implemented.
     at: call (modules/gdscript/gdscript_functions.cpp:788)
```

**Comment by balloonpopper** [comment]
Also managed to break it by opening room 5 (F6) and right clicking immediately. The screen was totally grey (transition in was about to start).
Console :
```
ESC (2022-07-22T18:37:18) T esc_compiler.gd: Compiling the next 3 lines into the group.
ESC (2022-07-22T18:37:18) T esc_compiler.gd: Parsing line       teleport player r5_r_exit.
ESC (2022-07-22T18:37:18) T esc_compiler.gd: Parsing line       set_angle player 270.
ESC (2022-07-22T18:37:18) T esc_compiler.gd: Parsing line       stop.
ESC (2022-07-22T18:37:18) D esc_room_manager.gd: Queuing room script event setup composed of 9 statements.
ESC (2022-07-22T18:37:18) D esc_event_manager.gd: Queueing event setup in channel _front.
ESC (2022-07-22T18:37:18) I esc_inputs_manager.gd: Right click on background at (988, 364).
ESC (2022-07-22T18:37:18) D esc_event_manager.gd: Interrupting queued event setup in channel _front...
ESC (2022-07-22T18:37:18) I esc_event.gd: Interrupting event setup ([Reference:3349]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3405]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3483]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3521]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3559]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3600]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3639]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3678]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3737]).
ESC (2022-07-22T18:37:18) I esc_group.gd: Interrupting event group ([Reference:3814]).
```
Same point - line 311

**Comment by StraToN** [comment]
@balloonpopper your remarks seem fixed with commit cb97550.

**Review by StraToN — APPROVED** [review]

**Comment by BHSDuncan** [comment]
@balloonpopper has found other issues--albeit edge cases--involving rapid clicking as a scene is starting. Just stating it here so we remember to address it.

**Comment by BHSDuncan** [comment]
Currently unable to reproduce in latest `develop`.

**Comment by balloonpopper** [comment]
Agreed, fixed in latest develop for both 3.4.4 and 3.5

**Review by balloonpopper — APPROVED** [review]

**Pull request merged**
