### PR TITLE
feature: Updated room 4 graphics

### PR DESCRIPTION
**Pull request by balloonpopper**
Updated room 4 graphics. Uses shadows to demonstrate lightmaps, winding path to demonstrate character scale, and a tree to demonstrate how you can walk behind objects.
image

### CODE REVIEW

**Review by StraToN — APPROVED** [review]
This looks amazing! :star_struck:

**Comment by BHSDuncan** [comment]
Looks good! But I'm a bit confused as to the transparency with the 9verb UI? Is that meant to demonstrate something in particular?

**Comment by StraToN** [comment]
> Looks good! But I'm a bit confused as to the transparency with the 9verb UI? Is that meant to demonstrate something in particular?

The PR doesn't seem to include such UI transparency change. Maybe that's a local change from @balloonpopper ?

**Comment by balloonpopper** [comment]
I haven't touched the UI interface in any of my changes, the transparency is how it always was.

**Comment by StraToN** [comment]
Ah I think you're right, the panel is transparent by default. LGTM @BHSDuncan

**Review by BHSDuncan — APPROVED** [review]

**Pull request merged**
