### PR TITLE
fix: prevents the same event from being queued multiple times in a row

### PR DESCRIPTION
**Pull request by BHSDuncan**
Fixes https://github.com/godot-escoria/escoria-issues/issues/245

### CODE REVIEW

**Comment by BHSDuncan** [comment]
Please test extensively. This PR should block multiple consecutive occurrences in an event queue and, if it's empty, also disallow the same event if it's currently already running.

This shouldn't affect ESC commands/events coming from ESC scripts.

Best test it out and make sure, though.

**Review by balloonpopper — CHANGES_REQUESTED** [review]
I can't reproduce the multiple events being queued issue with this fix. 

I did find a bug that I assume is related - if it's a new bug we can raise it accordingly.
If I right click the right painting, and while the character is walking to the painting I right click the left painting, Mark changes direction and walks to the left painting, however the interaction is the right painting's interaction.  (I can also do this in reverse and get painting 1's response talking to painting 2)

image

**Comment by BHSDuncan** [comment]
> I can't reproduce the multiple events being queued issue with this fix.
> 
> I did find a bug that I assume is related - if it's a new bug we can raise it accordingly. If I right click the right painting, and while the character is walking to the painting I right click the left painting, Mark changes direction and walks to the left painting, however the interaction is the right painting's interaction. (I can also do this in reverse and get painting 1's response talking to painting 2)
> 
> image

I don't think it would be related as this seems to be more related to interrupting. One way to be sure would be to see if this issue exists in `develop`. Could you try that and let us know? (I would but I need to look at a couple other things and I won't have time after to get to this.)

**Comment by balloonpopper** [comment]
The multiple talk issue is now https://github.com/godot-escoria/escoria-issues/issues/258

**Review by balloonpopper — APPROVED** [review]

**Review by StraToN — APPROVED** [review]

**Pull request merged**
