### PR TITLE
fix: Reset audio bus layout

### PR DESCRIPTION
**Pull request by dploeger**
Apparently Godot stores the settings of the audio bus layout in the editor locally somewhere. We set "default audio bus layout" to the resource file in this commit and when starting up the auditor, Godot loads the bus layout setting and applies it to the resource file.

This is just to reset the layout to 0db for each channel. If any dev should've changed the layout in their editor, they should reset their layout as well.

### CODE REVIEW

**Review by BHSDuncan — APPROVED** [review]

**Review by balloonpopper — CHANGES_REQUESTED** [review]
Can you add it to gitignore as part of the change? I can't see any reason to have it commit if a developer makes a local change.

**Comment by dploeger** [comment]
> Can you add it to gitignore as part of the change? I can't see any reason to have it commit if a developer makes a local change.

Hmm. We need this file. But putting it into .gitignore now would keep it in the history but just wouldn't record any new changes to it, right? And if you specifically want to record a change, you can force it. 

Never did it like this, but looks okay to me. I'd like your opinions on this, @BHSDuncan @StraToN

**Comment by BHSDuncan** [comment]
I'm ok with how this PR handles it. It might seem unlikely, but if a developer decides to set his/her own defaults, it might be better not to have it in the .gitignore file.

**Comment by balloonpopper** [comment]
My Godot editor settings aren't considered part of this repository - when I change my Godot editor's font or other options they don't become a suggested commit - why should my local sound settings be any different?
My thought : If the developer wants to commit their audio settings then let them update their own version of the .gitignore file - but I think the one attached to the demo repository should ignore local user-specific settings.

**Comment by dploeger** [comment]
As we have decided yesterday, added the file to the gitignore with a comment on how to ignore it there.

**Review by StraToN — APPROVED** [review]

**Comment by StraToN** [comment]
Thanks a lot !! :partying_face:

**Pull request merged**
