### PR TITLE
fix: room text is readable again

### PR DESCRIPTION
**Pull request by balloonpopper**
I didn't realise with the last update I'd made to the room background graphics I'd made the room description text unreadable. Fixed that by putting a coloured square behind it.

image

### CODE REVIEW

**Review by StraToN — DISMISSED** [review]

**Comment by StraToN** [comment]
Indeed I missed that file oO

**Comment by balloonpopper** [comment]
@dploeger / @StraToN - I create the graphics primarily in "paint dot net". "pdn" files are its version of the graphics file before I export the final version as png. I missed cleaning that one up behind myself before pushing the earlier change.

**Comment by StraToN** [comment]
Oh, right this is Paint.NET file type.

**Comment by dploeger** [comment]
Ah, that's why I didn't know about it. Windows software. brrrr. 🤣

**Review by dploeger — APPROVED** [review]
I'll approve this already given that you remove the .pdn file in another commit. Thanks 🎁

**Review by StraToN — APPROVED** [review]

**Comment by StraToN** [comment]
All good! Thanks a lot! 🥳

**Pull request merged**
