### PR TITLE
refactor: Whitespace removal from all .gd files

### PR DESCRIPTION
**Pull request by balloonpopper**
As Godot 3.4.2 automatically removes whitespace from gd files when the project is run, this PR is to fix all files.
After whitespace removal and testing the demo, Godot changed 2 files again, so these were recommitted. No further changes occurred after opening every room in the demo.

### CODE REVIEW

**Review by dploeger — APPROVED** [review]
Wonderful. Thanks! 🎁

**Review by BHSDuncan — APPROVED** [review]

**Review by StraToN — APPROVED** [review]

**Comment by StraToN** [comment]
I would have preferred a rebase instead of merging HEAD into this branch so that the PR doesn't hold code that's already in the target branch.

**Comment by dploeger** [comment]
> I would have preferred a rebase instead of merging HEAD into this branch so that the PR doesn't hold code that's already in the target branch.

Agreed as well. Can you maybe rebase it on develop?

**Comment by balloonpopper** [comment]
@StraToN @dploeger @BHSDuncan should be good now.

**Comment by dploeger** [comment]
lgtm

**Pull request merged**
