### PR TITLE
feat: Graphics update for room 5

### PR DESCRIPTION
**Pull request by balloonpopper**
image

### CODE REVIEW

**Review by BHSDuncan — APPROVED** [review]
Looks good just looking skimming through things.

**Review by dploeger — COMMENTED** [review]
Very nice. Especially the use of particles.

Do we need to add anything about the licenses of the new pictures?

**Comment by balloonpopper** [comment]
I grabbed a couple of Kenney pictures for room 1 and added license details to the repository at the time to cover them. 

Everything else I've drawn from scratch.
I don't have a licence requirement for my work, I'm trying to give back to the community.

If you feel it needs something,  maybe give the copyright to the Escoria project and say it's under a "you're free to do whatever you like with it" license? 🤷

**Comment by dploeger** [comment]
> I grabbed a couple of Kenney pictures for room 1 and added license details to the repository at the time to cover them.
> 
> Everything else I've drawn from scratch. I don't have a licence requirement for my work, I'm trying to give back to the community.
> 
> If you feel it needs something, maybe give the copyright to the Escoria project and say it's under a "you're free to do whatever you like with it" license? 🤷

Right. Then everything's fine. Thank you.

**Review by dploeger — APPROVED** [review]
Great. Thanks! 🎁

**Pull request merged**
