### PR TITLE
fix: "Give xyz with" should say "give xyz to" (#176)

### PR DESCRIPTION
**Pull request by ArturM**
Added ACTION_PREPS dictionary to settings/escoria/ui
Modified `esc_tooltip.gd` to make use of this dictionary.

Fixes https://github.com/godot-escoria/escoria-issues/issues/176

### CODE REVIEW

**Review by BHSDuncan — CHANGES_REQUESTED** [review]
The core code should have zero knowledge of the implementation. This issue is strictly related to the UI, and all UIs in Escoria are to be provided by the game developer using Escoria.

If you look in the 9-verbs UI we provide, you'll see that it's meant to have code that extends `ESCTooltip` and overrides `update_tooltip_text()`. This is likely where any manipulation of the tooltip text should go, since `ESCTooltip` itself prints nothing and has no language (in fact all it does is manage targets and display, really).

I would suggest the following:

- Remove any code from `escoria-core`.
- Update the 9-verbs UI as mentioned above.
- Even though this is meant to be an example of a UI, I'd still like to make sure we do things "properly". Specifically, I'm not sure if the prepositions belong in the project settings, especially if we ever want to localize those prepositions.

A good first attempt, but let's see about making the changes above.

Happy to discuss if needed.

**Comment by BHSDuncan** [comment]
Meant to fix #176.

**Comment by balloonpopper** [comment]
Can "preps" be renamed to "prepositions" too please?

**Review by StraToN — CHANGES_REQUESTED** [review]
I agree with @BHSDuncan's comment : your change should happen in the update_tooltip_text() function instead.
You can either make the prepositions dictionary a Project Setting related to 9-verbs UI plugin, or you can also set it as an exported variable of 9-verbs's tooltip so you can change it directly in the inspector.

**Comment by ArturM** [comment]
> I agree with @BHSDuncan's comment : your change should happen in the update_tooltip_text() function instead. You can either make the prepositions dictionary a Project Setting related to 9-verbs UI plugin, or you can also set it as an exported variable of 9-verbs's tooltip so you can change it directly in the inspector.

Reverted my changes in core. Made exported variable in `tooltip_action_changes.gd` and changed `update_tooltip_text()` to use this dictionary.

**Review by StraToN — APPROVED** [review]

**Comment by StraToN** [comment]
LGTM. Thanks!

**Comment by BHSDuncan** [comment]
Changes look ok to me, too, but before I accept them I'd like @balloonpopper to test this and get his sign-off before we merge. Thanks!

**Review by BHSDuncan — APPROVED** [review]

**Pull request merged**
